<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\Companies.txt" />
    <None Remove="TestData\Roles.txt" />
    <None Remove="TestData\SeedData\ShopStock.txt" />
    <None Remove="TestData\Users.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestData\SeedData\Companies.txt">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="TestData\SeedData\Roles.txt">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="TestData\SeedData\ShopStock.txt">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="TestData\SeedData\Users.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.TestSupport" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAuthorize\DataAuthorize.csproj" />
    <ProjectReference Include="..\DataKeyParts\DataKeyParts.csproj" />
    <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
    <ProjectReference Include="..\FeatureAuthorize\FeatureAuthorize.csproj" />
    <ProjectReference Include="..\PermissionAccessControl2\PermissionAccessControl2.csproj" />
    <ProjectReference Include="..\PermissionParts\PermissionParts.csproj" />
    <ProjectReference Include="..\RefreshClaimsParts\RefreshClaimsParts.csproj" />
    <ProjectReference Include="..\ScopeAuthorize\ScopeAuthorize.csproj" />
    <ProjectReference Include="..\ServiceLayer\ServiceLayer.csproj" />
    <ProjectReference Include="..\UserImpersonation\UserImpersonation.csproj" />
  </ItemGroup>

</Project>
